version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
    ports:
      - 8080:8080
    command: [ "start-dev"]
    volumes:
      - keycloakVolume:/opt/keycloak/data
volumes:
  keycloakVolume: